/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.JDBCUtil;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static view.JanelaLogin.esp;

/**
 *
 * @author Giulia
 */
public class JanelaCadastrarNovoEsp extends javax.swing.JFrame {

    private Connection connection = null;
    private Statement stdados = null;
    private ResultSet rsdados = null;
    //JanelaLogin jl = new JanelaLogin();
    
    
    /**
     * Creates new form JanelaCadastrarNovoEsp
     */
    public JanelaCadastrarNovoEsp() {
        initComponents();
        AcessaBD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CxNome = new javax.swing.JTextField();
        CxUser = new javax.swing.JTextField();
        CxSenha = new javax.swing.JPasswordField();
        CxConfirmarSenha = new javax.swing.JPasswordField();
        BtConfirmar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel3.setText("Login:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel4.setText("Senha:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel5.setText("Confirme a senha:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Exotc350 Bd BT", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 0));
        jLabel6.setText("Cadastre um novo especialista");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        CxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxNomeActionPerformed(evt);
            }
        });
        getContentPane().add(CxNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 510, -1));
        getContentPane().add(CxUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 510, -1));

        CxSenha.setText("123456");
        CxSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CxSenhaMouseClicked(evt);
            }
        });
        getContentPane().add(CxSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 510, -1));

        CxConfirmarSenha.setText("123456");
        getContentPane().add(CxConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 510, -1));

        BtConfirmar.setBackground(new java.awt.Color(0, 51, 0));
        BtConfirmar.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        BtConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        BtConfirmar.setText("CONFIRMAR");
        BtConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(BtConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 180, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/fundo_cadastrar_esp.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxNomeActionPerformed

    private void BtConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConfirmarActionPerformed
        darCommit();
    }//GEN-LAST:event_BtConfirmarActionPerformed

    private void CxSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CxSenhaMouseClicked
        // TODO add your handling code here:
        CxSenha.setText("");
        CxConfirmarSenha.setText("");
    }//GEN-LAST:event_CxSenhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarNovoEsp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarNovoEsp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarNovoEsp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarNovoEsp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCadastrarNovoEsp().setVisible(true);
            }
        });
    }
    
    public void darCommit(){
        try {
            // TODO add your handling code here            
            if (usuarioExistente() && senhaIgual()) {
                limparCxs(); 
            } else {
                addBD();
                JOptionPane.showMessageDialog(null, "USUARIO CADASTRADO COM SUCESSO", "SUCCESS", 1);
                limparCxs();
                this.dispose();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(JanelaCadastrarNovoEsp.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    
    public void limparCxs() {
        CxNome.setText("");
        CxUser.setText("");
        CxSenha.setText("");
        CxConfirmarSenha.setText("");
    }
    
    
    public boolean senhaIgual() {
        if (CxSenha.getText().equals(CxConfirmarSenha.getText())) {
            System.out.println("Senha correta");
            return false;
        } else {
            System.out.println("Senhas incorretas");
            JOptionPane.showMessageDialog(null, "SENHAS DIFERENTES", "Error", 0);
            return true;
        }
    
    }
    
    public boolean usuarioExistente () throws SQLException {
        boolean existe=false;
        String user = CxUser.getText();
        
        try {
            Statement st = connection.createStatement();
            String query = "select * from especialista where login='"+user+"'";
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()){
                existe = true;
            }
            
            if (existe) {
                JOptionPane.showMessageDialog(null, "LOGIN JA EXISTE", "Error", 1);  
            } //else {
//                JOptionPane.showMessageDialog(null, "USUARIO VALIDO", "CADASTRO", 1);
//            }
        } catch (SQLException ex) {
            Logger.getLogger(JanelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        return existe;
    }
    
    public void addBD() throws SQLException{
        String query = "INSERT INTO especialista VALUES ('"+CxNome.getText()+"',"
                + "'"+CxUser.getText()+"','"+CxSenha.getText()+"')";
        
        try {
            Statement st = connection.createStatement();
            st.executeUpdate(query);
        } catch (SQLException ex) {
            Logger.getLogger(JanelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }
    
    //////////////////////////////////
    public boolean AcessaBD() {
        try {
            String path = System.getProperty("user.dir")+"/src/control/";
            File config_file = new File(path, "configuracaobd.properties");
            JDBCUtil.init(config_file);

            connection = JDBCUtil.getConnection();
            connection.setAutoCommit(true);//configuracao necessaria para confirmacao ou nao de alteracoes no banco de dados.


        } catch (ClassNotFoundException erro) {
            System.out.println("Falha ao carregar o driver JDBC." + erro);
            return false;
        } catch (IOException erro) {
            System.out.println("Falha ao carregar o arquivo de configuração." + erro);
            return false;
        } catch (SQLException erro) {
            System.out.println("Falha na conexao, comando sql = " + erro);
            return false;
        }
        return true;
    }
    
    ////////////////////////////////////
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtConfirmar;
    private javax.swing.JPasswordField CxConfirmarSenha;
    private javax.swing.JTextField CxNome;
    private javax.swing.JPasswordField CxSenha;
    private javax.swing.JTextField CxUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
